/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : spark.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Spark.h"

int _memcmp(const void *p1, const void *p2, unsigned int size) {
    unsigned int i;
    for(i = 0; i < size; ++ i) {
        if(*((char*)p1 + i) > *((char*)p2 + i))
            return 1;
        if(*((char*)p1 + i) < *((char*)p2 + i))
            return -1;
    }
    return 0;
} 
 
void _memset(void *msg_ptr, char init_val, unsigned int size) {
    unsigned int i;
    for(i = 0; i < size; ++ i)
        *((char*)msg_ptr + i) = init_val;
}

int varint_packed_size(unsigned long value) {
    if ((value & (0xffffffff <<  7)) == 0) return 1;
    if ((value & (0xffffffff << 14)) == 0) return 2;
    if ((value & (0xffffffff << 21)) == 0) return 3;
    if ((value & (0xffffffff << 28)) == 0) return 4;
    return 5;  
}

int write_raw_byte(char value, void *_buffer, int offset) {
    *((char *)_buffer + offset) = value;
    return ++offset;
}

/** Write a little-endian 32-bit integer. */
int write_raw_little_endian32(unsigned long value, void *_buffer, int offset) {
    offset = write_raw_byte((char)((value      ) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >>  8) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 16) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 24) & 0xFF), _buffer, offset);
    
    return offset;
}

/** Write a little-endian 64-bit integer. */
int write_raw_little_endian64(unsigned long long value, void *_buffer, int offset) {
    offset = write_raw_byte((char)((value      ) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >>  8) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 16) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 24) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 32) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 40) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 48) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 56) & 0xFF), _buffer, offset);
    
    return offset;
}

int write_raw_varint32(unsigned long value, void *_buffer, int offset) {
    while (1) {
        if ((value & ~0x7F) == 0) {
            offset = write_raw_byte((char)value, _buffer, offset);
            return offset;
        } else {
            offset = write_raw_byte((char)((value & 0x7F) | 0x80), _buffer, offset);
            value = value >> 7;
        }
    }
    return offset;
}

int write_raw_varint64(unsigned long long value, void *_buffer, int offset) {
    while (1) {
        if ((value & ~0x7FL) == 0) {
            offset = write_raw_byte((char)value, _buffer, offset);
            return offset;
        } else {
            offset = write_raw_byte((char)((value & 0x7F) | 0x80), _buffer, offset);
            value = value >> 7;
        }
    }
    return offset;
}

int write_raw_bytes(char *bytes, int bytes_size, void *_buffer, int offset) {
    int i; 
    for(i = 0; i < bytes_size; ++ i) {
        offset = write_raw_byte((char)*(bytes + i), _buffer, offset);
    }
    
    return offset;   
}

unsigned long encode_zig_zag32(signed long n) {
    /* Note:  the right-shift must be arithmetic. */
    return (n << 1) ^ (n >> 31);
}

unsigned long long encode_zig_zag64(signed long long n) {
    /* Note:  the right-shift must be arithmetic. */
    return (n << 1) ^ (n >> 63);
} 

signed long decode_zig_zag32(unsigned long n) {
    return (n >> 1) ^ -(n & 1);
}

signed long long decode_zig_zag64(unsigned long long n) {
    return (n >> 1) ^ -(n & 1);
}

int read_raw_byte(char *tag, void *_buffer, int offset) {
    *tag = *((char *) _buffer + offset);
    
    return ++offset;
}

/** Read a 32-bit little-endian integer from the stream. */
int read_raw_little_endian32(unsigned long *tag, void *_buffer, int offset) {
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b1 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b2 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b3 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b4 = (char) *tag;
    
    *tag = (((unsigned long)b1 & 0xff)      ) |
           (((unsigned long)b2 & 0xff) <<  8) |
           (((unsigned long)b3 & 0xff) << 16) |
           (((unsigned long)b4 & 0xff) << 24);
           
    return offset;
}

/** Read a 64-bit little-endian integer from the stream. */
int read_raw_little_endian64(unsigned long long *tag, void *_buffer, int offset) {
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b1 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b2 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b3 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b4 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b5 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b6 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b7 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b8 = (char) *tag;
    
    *tag = (((unsigned long long)b1 & 0xff)      ) |
           (((unsigned long long)b2 & 0xff) <<  8) |
           (((unsigned long long)b3 & 0xff) << 16) |
           (((unsigned long long)b4 & 0xff) << 24) |
           (((unsigned long long)b5 & 0xff) << 32) |
           (((unsigned long long)b6 & 0xff) << 40) |
           (((unsigned long long)b7 & 0xff) << 48) |
           (((unsigned long long)b8 & 0xff) << 56);
           
    return offset;
}

int read_raw_varint32(unsigned long *tag, void *_buffer, int offset) {
    signed char result;
    
    offset = read_raw_byte((char *)&result, _buffer, offset);
    if (result >= 0) {
        *tag = result;
        return offset;
    }
    *tag = result & 0x7f;
    offset = read_raw_byte((char *)&result, _buffer, offset);
    if (result >= 0) {
        *tag |= result << 7;
    } else {
        *tag |= (result & 0x7f) << 7;
        offset = read_raw_byte((char *)&result, _buffer, offset);
        if (result >= 0) {
            *tag |= result << 14;
        } else {
            *tag |= (result & 0x7f) << 14;
            offset = read_raw_byte((char *)&result, _buffer, offset);
            if (result >= 0) {
                *tag |= ((unsigned long)result) << 21;
            } else {
                *tag |= (((unsigned long)result) & 0x7f) << 21;
                offset = read_raw_byte((char *)&result, _buffer, offset);
                *tag |= ((unsigned long)result) << 28;
                if (result < 0) {
                    /* Discard upper 32 bits. */
                    int i;
                    for (i = 0; i < 5; ++ i) {
                        offset = read_raw_byte((char *)&result, _buffer, offset);
                        if (result >= 0) {
                            return offset;
                        }
                    }
                    /* Invalid state. */
                }
            }
        }
    }
    return offset;
}

int read_raw_varint64(unsigned long long *tag, void *_buffer, int offset) {
    short shift = 0;
    signed char b;
    *tag = 0;
    while (shift < 64) {
        offset = read_raw_byte((char *)&b, _buffer, offset);
        *tag |= (unsigned long long)(b & 0x7F) << shift;
        if ((b & 0x80) == 0) {
            return offset;
        }
        shift += 7;
    }
    /* return error code. */
    return -1;
}

int can_read_raw_varint32(void *_buffer, int offset, int length) {
    signed char c;
    
    /* Bound length to valid range [0..5]. */
    if (length < 0) length = 0; else
    if (length > 5) length = 5;
    
    while (length > 0) {
        offset = read_raw_byte((char *)&c, _buffer, offset);
        if (c >= 0) {
            return 1; /* Can read (1 == true). */
        }
        length--;
    }
    
    return 0; /* Cannot read (0 == false). */
}

int can_read_raw_varint64(void *_buffer, int offset, int length) {
    signed char c;
    
    /* Bound length to valid range [0..5]. */
    if (length < 0) length = 0; else
    if (length > 10) length = 10;
    
    while (length > 0) {
        offset = read_raw_byte((char *)&c, _buffer, offset);
        if (c >= 0) {
            return 1; /* Can read (1 == true). */
        }
        length--;
    }
    
    return 0; /* Cannot read (0 == false). */
}

int Message_can_read_delimited_from(void *_buffer, int offset, unsigned int length) {
    unsigned long size;
    int payload_offset;

    if (length <= 0) return 0; /* Cannot read from empty or invalid message. */

    if (!can_read_raw_varint32(_buffer, offset, length)) {
        return 0; /* Could not even read the preceding size as varint32. */
    }

    payload_offset = read_raw_varint32(&size, _buffer, offset);
    length = length - (payload_offset - offset);

    return (length >= size) ? 1 : 0;
}

unsigned long Message_get_delimited_size(void *_buffer, int offset) {
    unsigned long size = 0;
    int old_offset = offset;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    
    return size + offset - old_offset;
}

/*******************************************************************
* Enumeration: Spark.proto, line 64
*******************************************************************/
int Type_write_with_tag(enum Type *_Type, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+0, _buffer, offset);
    /* Write content.*/
    offset = write_raw_varint32(*_Type, _buffer, offset);
    
    return offset;
}


/*******************************************************************
 * Message: Spark.proto, line 6
 *******************************************************************/

void Chunk_clear(struct Chunk *_Chunk) {
	_memset(_Chunk, 0, sizeof(struct Chunk));
}

void Chunk_init_optional_attributes(struct Chunk *_Chunk) {
	_Chunk->_crc_len = 0;
	
	
	_Chunk->_length = 0;
	
	_Chunk->_data_len = 0;
	
	
}

int Chunk_is_default_message(struct Chunk *_Chunk) {
    return _Chunk->_crc_len == 0
    
     && _Chunk->_length == 0
    
     && _Chunk->_data_len == 0
    ;
}

int Chunk_write(struct Chunk *_Chunk, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_Chunk->_crc_len != 1
	    || _Chunk->_crc[0] != '0') {
		offset = write_raw_varint32((1<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_Chunk->_crc_len, _buffer, offset);
	    offset = write_raw_bytes(_Chunk->_crc, _Chunk->_crc_len, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Chunk->_length != 0) {
		offset = write_raw_varint32((2<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Chunk->_length, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Chunk->_data_len != 1
	    || _Chunk->_data[0] != '0') {
		offset = write_raw_varint32((3<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_Chunk->_data_len, _buffer, offset);
	    offset = write_raw_bytes(_Chunk->_data, _Chunk->_data_len, _buffer, offset);
	}
	
	return offset;
}

int Chunk_write_with_tag(struct Chunk *_Chunk, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = Chunk_write_delimited_to(_Chunk, _buffer, offset);
	
	return offset;
}

int Chunk_write_delimited_to(struct Chunk *_Chunk, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = Chunk_write(_Chunk, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int Chunk_read(void *_buffer, struct Chunk *_Chunk, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	Chunk_clear(_Chunk);
	/* Assign the optional attributes. */
	Chunk_init_optional_attributes(_Chunk);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _Chunk._crc */
	        case 1 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Chunk->_crc_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_Chunk->_crc + i), _buffer, offset);
	        	break;
	        /* tag of: _Chunk._length */
	        case 2 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Chunk->_length = tag;
	        	break;
	        /* tag of: _Chunk._data */
	        case 3 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Chunk->_data_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_Chunk->_data + i), _buffer, offset);
	        	break;
	    }
	}
	
	return offset;
}

int Chunk_read_delimited_from(void *_buffer, struct Chunk *_Chunk, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	Chunk_read(_buffer, _Chunk, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 11
 *******************************************************************/

void ChunkReceived_clear(struct ChunkReceived *_ChunkReceived) {
	_memset(_ChunkReceived, 0, sizeof(struct ChunkReceived));
}

void ChunkReceived_init_optional_attributes(struct ChunkReceived *_ChunkReceived) {
	_ChunkReceived->_counter = 0;
	
	_ChunkReceived->_crc_len = 0;
	
	
}

int ChunkReceived_is_default_message(struct ChunkReceived *_ChunkReceived) {
    return _ChunkReceived->_counter == 0
    
     && _ChunkReceived->_crc_len == 0
    ;
}

int ChunkReceived_write(struct ChunkReceived *_ChunkReceived, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_ChunkReceived->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_ChunkReceived->_counter, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_ChunkReceived->_crc_len != 1
	    || _ChunkReceived->_crc[0] != '0') {
		offset = write_raw_varint32((2<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_ChunkReceived->_crc_len, _buffer, offset);
	    offset = write_raw_bytes(_ChunkReceived->_crc, _ChunkReceived->_crc_len, _buffer, offset);
	}
	
	return offset;
}

int ChunkReceived_write_with_tag(struct ChunkReceived *_ChunkReceived, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = ChunkReceived_write_delimited_to(_ChunkReceived, _buffer, offset);
	
	return offset;
}

int ChunkReceived_write_delimited_to(struct ChunkReceived *_ChunkReceived, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = ChunkReceived_write(_ChunkReceived, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int ChunkReceived_read(void *_buffer, struct ChunkReceived *_ChunkReceived, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	ChunkReceived_clear(_ChunkReceived);
	/* Assign the optional attributes. */
	ChunkReceived_init_optional_attributes(_ChunkReceived);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _ChunkReceived._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_ChunkReceived->_counter = tag;
	        	break;
	        /* tag of: _ChunkReceived._crc */
	        case 2 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_ChunkReceived->_crc_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_ChunkReceived->_crc + i), _buffer, offset);
	        	break;
	    }
	}
	
	return offset;
}

int ChunkReceived_read_delimited_from(void *_buffer, struct ChunkReceived *_ChunkReceived, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	ChunkReceived_read(_buffer, _ChunkReceived, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 15
 *******************************************************************/

void Event_clear(struct Event *_Event) {
	_memset(_Event, 0, sizeof(struct Event));
}

void Event_init_optional_attributes(struct Event *_Event) {
	_Event->_counter = 0;
	
	_Event->_name_len = 0;
	
	
	_Event->_data_len = 0;
	
	
}

int Event_is_default_message(struct Event *_Event) {
    return _Event->_counter == 0
    
     && _Event->_name_len == 0
    
     && _Event->_data_len == 0
    ;
}

int Event_write(struct Event *_Event, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_Event->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Event->_counter, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Event->_name_len != 1
	    || _Event->_name[0] != '0') {
		offset = write_raw_varint32((2<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_Event->_name_len, _buffer, offset);
	    offset = write_raw_bytes(_Event->_name, _Event->_name_len, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Event->_data_len != 1
	    || _Event->_data[0] != '0') {
		offset = write_raw_varint32((3<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_Event->_data_len, _buffer, offset);
	    offset = write_raw_bytes(_Event->_data, _Event->_data_len, _buffer, offset);
	}
	
	return offset;
}

int Event_write_with_tag(struct Event *_Event, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = Event_write_delimited_to(_Event, _buffer, offset);
	
	return offset;
}

int Event_write_delimited_to(struct Event *_Event, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = Event_write(_Event, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int Event_read(void *_buffer, struct Event *_Event, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	Event_clear(_Event);
	/* Assign the optional attributes. */
	Event_init_optional_attributes(_Event);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _Event._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Event->_counter = tag;
	        	break;
	        /* tag of: _Event._name */
	        case 2 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Event->_name_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_Event->_name + i), _buffer, offset);
	        	break;
	        /* tag of: _Event._data */
	        case 3 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Event->_data_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_Event->_data + i), _buffer, offset);
	        	break;
	    }
	}
	
	return offset;
}

int Event_read_delimited_from(void *_buffer, struct Event *_Event, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	Event_read(_buffer, _Event, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 20
 *******************************************************************/

void FunctionCall_clear(struct FunctionCall *_FunctionCall) {
	_memset(_FunctionCall, 0, sizeof(struct FunctionCall));
}

void FunctionCall_init_optional_attributes(struct FunctionCall *_FunctionCall) {
	_FunctionCall->_counter = 0;
	
}

int FunctionCall_is_default_message(struct FunctionCall *_FunctionCall) {
    return _FunctionCall->_counter == 0
    ;
}

int FunctionCall_write(struct FunctionCall *_FunctionCall, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_FunctionCall->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_FunctionCall->_counter, _buffer, offset);
	}
	
	return offset;
}

int FunctionCall_write_with_tag(struct FunctionCall *_FunctionCall, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = FunctionCall_write_delimited_to(_FunctionCall, _buffer, offset);
	
	return offset;
}

int FunctionCall_write_delimited_to(struct FunctionCall *_FunctionCall, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = FunctionCall_write(_FunctionCall, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int FunctionCall_read(void *_buffer, struct FunctionCall *_FunctionCall, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	FunctionCall_clear(_FunctionCall);
	/* Assign the optional attributes. */
	FunctionCall_init_optional_attributes(_FunctionCall);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _FunctionCall._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_FunctionCall->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int FunctionCall_read_delimited_from(void *_buffer, struct FunctionCall *_FunctionCall, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	FunctionCall_read(_buffer, _FunctionCall, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 24
 *******************************************************************/

void FunctionReturn_clear(struct FunctionReturn *_FunctionReturn) {
	_memset(_FunctionReturn, 0, sizeof(struct FunctionReturn));
}

void FunctionReturn_init_optional_attributes(struct FunctionReturn *_FunctionReturn) {
	_FunctionReturn->_counter = 0;
	
}

int FunctionReturn_is_default_message(struct FunctionReturn *_FunctionReturn) {
    return _FunctionReturn->_counter == 0
    ;
}

int FunctionReturn_write(struct FunctionReturn *_FunctionReturn, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_FunctionReturn->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_FunctionReturn->_counter, _buffer, offset);
	}
	
	return offset;
}

int FunctionReturn_write_with_tag(struct FunctionReturn *_FunctionReturn, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = FunctionReturn_write_delimited_to(_FunctionReturn, _buffer, offset);
	
	return offset;
}

int FunctionReturn_write_delimited_to(struct FunctionReturn *_FunctionReturn, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = FunctionReturn_write(_FunctionReturn, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int FunctionReturn_read(void *_buffer, struct FunctionReturn *_FunctionReturn, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	FunctionReturn_clear(_FunctionReturn);
	/* Assign the optional attributes. */
	FunctionReturn_init_optional_attributes(_FunctionReturn);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _FunctionReturn._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_FunctionReturn->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int FunctionReturn_read_delimited_from(void *_buffer, struct FunctionReturn *_FunctionReturn, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	FunctionReturn_read(_buffer, _FunctionReturn, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 29
 *******************************************************************/

void Hello_clear(struct Hello *_Hello) {
	_memset(_Hello, 0, sizeof(struct Hello));
}

void Hello_init_optional_attributes(struct Hello *_Hello) {
	_Hello->_counter = 0;
	
}

int Hello_is_default_message(struct Hello *_Hello) {
    return _Hello->_counter == 0
    ;
}

int Hello_write(struct Hello *_Hello, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_Hello->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Hello->_counter, _buffer, offset);
	}
	
	return offset;
}

int Hello_write_with_tag(struct Hello *_Hello, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = Hello_write_delimited_to(_Hello, _buffer, offset);
	
	return offset;
}

int Hello_write_delimited_to(struct Hello *_Hello, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = Hello_write(_Hello, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int Hello_read(void *_buffer, struct Hello *_Hello, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	Hello_clear(_Hello);
	/* Assign the optional attributes. */
	Hello_init_optional_attributes(_Hello);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _Hello._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Hello->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int Hello_read_delimited_from(void *_buffer, struct Hello *_Hello, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	Hello_read(_buffer, _Hello, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 32
 *******************************************************************/

void Ignored_clear(struct Ignored *_Ignored) {
	_memset(_Ignored, 0, sizeof(struct Ignored));
}

void Ignored_init_optional_attributes(struct Ignored *_Ignored) {
	_Ignored->_counter = 0;
	
	_Ignored->_received = 0;
	
}

int Ignored_is_default_message(struct Ignored *_Ignored) {
    return _Ignored->_counter == 0
    
     && _Ignored->_received == 0
    ;
}

int Ignored_write(struct Ignored *_Ignored, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_Ignored->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Ignored->_counter, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Ignored->_received != 0) {
		offset = write_raw_varint32((2<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Ignored->_received, _buffer, offset);
	}
	
	return offset;
}

int Ignored_write_with_tag(struct Ignored *_Ignored, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = Ignored_write_delimited_to(_Ignored, _buffer, offset);
	
	return offset;
}

int Ignored_write_delimited_to(struct Ignored *_Ignored, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = Ignored_write(_Ignored, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int Ignored_read(void *_buffer, struct Ignored *_Ignored, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	Ignored_clear(_Ignored);
	/* Assign the optional attributes. */
	Ignored_init_optional_attributes(_Ignored);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _Ignored._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Ignored->_counter = tag;
	        	break;
	        /* tag of: _Ignored._received */
	        case 2 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Ignored->_received = tag;
	        	break;
	    }
	}
	
	return offset;
}

int Ignored_read_delimited_from(void *_buffer, struct Ignored *_Ignored, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	Ignored_read(_buffer, _Ignored, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 36
 *******************************************************************/

void KeyChange_clear(struct KeyChange *_KeyChange) {
	_memset(_KeyChange, 0, sizeof(struct KeyChange));
}

void KeyChange_init_optional_attributes(struct KeyChange *_KeyChange) {
	_KeyChange->_counter = 0;
	
	_KeyChange->_ciphertext_len = 0;
	
	
	_KeyChange->_signature_len = 0;
	
	
}

int KeyChange_is_default_message(struct KeyChange *_KeyChange) {
    return _KeyChange->_counter == 0
    
     && _KeyChange->_ciphertext_len == 0
    
     && _KeyChange->_signature_len == 0
    ;
}

int KeyChange_write(struct KeyChange *_KeyChange, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_KeyChange->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_KeyChange->_counter, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_KeyChange->_ciphertext_len != 1
	    || _KeyChange->_ciphertext[0] != '0') {
		offset = write_raw_varint32((2<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_KeyChange->_ciphertext_len, _buffer, offset);
	    offset = write_raw_bytes(_KeyChange->_ciphertext, _KeyChange->_ciphertext_len, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_KeyChange->_signature_len != 1
	    || _KeyChange->_signature[0] != '0') {
		offset = write_raw_varint32((3<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_KeyChange->_signature_len, _buffer, offset);
	    offset = write_raw_bytes(_KeyChange->_signature, _KeyChange->_signature_len, _buffer, offset);
	}
	
	return offset;
}

int KeyChange_write_with_tag(struct KeyChange *_KeyChange, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = KeyChange_write_delimited_to(_KeyChange, _buffer, offset);
	
	return offset;
}

int KeyChange_write_delimited_to(struct KeyChange *_KeyChange, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = KeyChange_write(_KeyChange, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int KeyChange_read(void *_buffer, struct KeyChange *_KeyChange, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	KeyChange_clear(_KeyChange);
	/* Assign the optional attributes. */
	KeyChange_init_optional_attributes(_KeyChange);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _KeyChange._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_KeyChange->_counter = tag;
	        	break;
	        /* tag of: _KeyChange._ciphertext */
	        case 2 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_KeyChange->_ciphertext_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_KeyChange->_ciphertext + i), _buffer, offset);
	        	break;
	        /* tag of: _KeyChange._signature */
	        case 3 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_KeyChange->_signature_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_KeyChange->_signature + i), _buffer, offset);
	        	break;
	    }
	}
	
	return offset;
}

int KeyChange_read_delimited_from(void *_buffer, struct KeyChange *_KeyChange, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	KeyChange_read(_buffer, _KeyChange, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 41
 *******************************************************************/

void UpdateBegin_clear(struct UpdateBegin *_UpdateBegin) {
	_memset(_UpdateBegin, 0, sizeof(struct UpdateBegin));
}

void UpdateBegin_init_optional_attributes(struct UpdateBegin *_UpdateBegin) {
	_UpdateBegin->_counter = 0;
	
}

int UpdateBegin_is_default_message(struct UpdateBegin *_UpdateBegin) {
    return _UpdateBegin->_counter == 0
    ;
}

int UpdateBegin_write(struct UpdateBegin *_UpdateBegin, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_UpdateBegin->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_UpdateBegin->_counter, _buffer, offset);
	}
	
	return offset;
}

int UpdateBegin_write_with_tag(struct UpdateBegin *_UpdateBegin, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = UpdateBegin_write_delimited_to(_UpdateBegin, _buffer, offset);
	
	return offset;
}

int UpdateBegin_write_delimited_to(struct UpdateBegin *_UpdateBegin, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = UpdateBegin_write(_UpdateBegin, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int UpdateBegin_read(void *_buffer, struct UpdateBegin *_UpdateBegin, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	UpdateBegin_clear(_UpdateBegin);
	/* Assign the optional attributes. */
	UpdateBegin_init_optional_attributes(_UpdateBegin);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _UpdateBegin._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_UpdateBegin->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int UpdateBegin_read_delimited_from(void *_buffer, struct UpdateBegin *_UpdateBegin, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	UpdateBegin_read(_buffer, _UpdateBegin, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 44
 *******************************************************************/

void UpdateDone_clear(struct UpdateDone *_UpdateDone) {
	_memset(_UpdateDone, 0, sizeof(struct UpdateDone));
}

void UpdateDone_init_optional_attributes(struct UpdateDone *_UpdateDone) {
	_UpdateDone->_counter = 0;
	
}

int UpdateDone_is_default_message(struct UpdateDone *_UpdateDone) {
    return _UpdateDone->_counter == 0
    ;
}

int UpdateDone_write(struct UpdateDone *_UpdateDone, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_UpdateDone->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_UpdateDone->_counter, _buffer, offset);
	}
	
	return offset;
}

int UpdateDone_write_with_tag(struct UpdateDone *_UpdateDone, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = UpdateDone_write_delimited_to(_UpdateDone, _buffer, offset);
	
	return offset;
}

int UpdateDone_write_delimited_to(struct UpdateDone *_UpdateDone, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = UpdateDone_write(_UpdateDone, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int UpdateDone_read(void *_buffer, struct UpdateDone *_UpdateDone, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	UpdateDone_clear(_UpdateDone);
	/* Assign the optional attributes. */
	UpdateDone_init_optional_attributes(_UpdateDone);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _UpdateDone._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_UpdateDone->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int UpdateDone_read_delimited_from(void *_buffer, struct UpdateDone *_UpdateDone, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	UpdateDone_read(_buffer, _UpdateDone, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 47
 *******************************************************************/

void UpdateReady_clear(struct UpdateReady *_UpdateReady) {
	_memset(_UpdateReady, 0, sizeof(struct UpdateReady));
}

void UpdateReady_init_optional_attributes(struct UpdateReady *_UpdateReady) {
	_UpdateReady->_counter = 0;
	
}

int UpdateReady_is_default_message(struct UpdateReady *_UpdateReady) {
    return _UpdateReady->_counter == 0
    ;
}

int UpdateReady_write(struct UpdateReady *_UpdateReady, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_UpdateReady->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_UpdateReady->_counter, _buffer, offset);
	}
	
	return offset;
}

int UpdateReady_write_with_tag(struct UpdateReady *_UpdateReady, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = UpdateReady_write_delimited_to(_UpdateReady, _buffer, offset);
	
	return offset;
}

int UpdateReady_write_delimited_to(struct UpdateReady *_UpdateReady, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = UpdateReady_write(_UpdateReady, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int UpdateReady_read(void *_buffer, struct UpdateReady *_UpdateReady, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	UpdateReady_clear(_UpdateReady);
	/* Assign the optional attributes. */
	UpdateReady_init_optional_attributes(_UpdateReady);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _UpdateReady._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_UpdateReady->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int UpdateReady_read_delimited_from(void *_buffer, struct UpdateReady *_UpdateReady, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	UpdateReady_read(_buffer, _UpdateReady, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 50
 *******************************************************************/

void VariableRequest_clear(struct VariableRequest *_VariableRequest) {
	_memset(_VariableRequest, 0, sizeof(struct VariableRequest));
}

void VariableRequest_init_optional_attributes(struct VariableRequest *_VariableRequest) {
	_VariableRequest->_counter = 0;
	
}

int VariableRequest_is_default_message(struct VariableRequest *_VariableRequest) {
    return _VariableRequest->_counter == 0
    ;
}

int VariableRequest_write(struct VariableRequest *_VariableRequest, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_VariableRequest->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_VariableRequest->_counter, _buffer, offset);
	}
	
	return offset;
}

int VariableRequest_write_with_tag(struct VariableRequest *_VariableRequest, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = VariableRequest_write_delimited_to(_VariableRequest, _buffer, offset);
	
	return offset;
}

int VariableRequest_write_delimited_to(struct VariableRequest *_VariableRequest, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = VariableRequest_write(_VariableRequest, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int VariableRequest_read(void *_buffer, struct VariableRequest *_VariableRequest, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	VariableRequest_clear(_VariableRequest);
	/* Assign the optional attributes. */
	VariableRequest_init_optional_attributes(_VariableRequest);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _VariableRequest._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_VariableRequest->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int VariableRequest_read_delimited_from(void *_buffer, struct VariableRequest *_VariableRequest, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	VariableRequest_read(_buffer, _VariableRequest, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 54
 *******************************************************************/

void VariableValue_clear(struct VariableValue *_VariableValue) {
	_memset(_VariableValue, 0, sizeof(struct VariableValue));
}

void VariableValue_init_optional_attributes(struct VariableValue *_VariableValue) {
	_VariableValue->_counter = 0;
	
}

int VariableValue_is_default_message(struct VariableValue *_VariableValue) {
    return _VariableValue->_counter == 0
    ;
}

int VariableValue_write(struct VariableValue *_VariableValue, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_VariableValue->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_VariableValue->_counter, _buffer, offset);
	}
	
	return offset;
}

int VariableValue_write_with_tag(struct VariableValue *_VariableValue, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = VariableValue_write_delimited_to(_VariableValue, _buffer, offset);
	
	return offset;
}

int VariableValue_write_delimited_to(struct VariableValue *_VariableValue, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = VariableValue_write(_VariableValue, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int VariableValue_read(void *_buffer, struct VariableValue *_VariableValue, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	VariableValue_clear(_VariableValue);
	/* Assign the optional attributes. */
	VariableValue_init_optional_attributes(_VariableValue);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _VariableValue._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_VariableValue->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int VariableValue_read_delimited_from(void *_buffer, struct VariableValue *_VariableValue, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	VariableValue_read(_buffer, _VariableValue, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Spark.proto, line 80
 *******************************************************************/

void Envelope_clear(struct Envelope *_Envelope) {
	_memset(_Envelope, 0, sizeof(struct Envelope));
}

void Envelope_init_optional_attributes(struct Envelope *_Envelope) {
	_Envelope->_type = 0;
	
	VariableRequest_init_optional_attributes(&_Envelope->_variablerequest);
	
	VariableValue_init_optional_attributes(&_Envelope->_variablevalue);
	
	FunctionCall_init_optional_attributes(&_Envelope->_functioncall);
	
	FunctionReturn_init_optional_attributes(&_Envelope->_functionreturn);
	
	Event_init_optional_attributes(&_Envelope->_event);
	
	Ignored_init_optional_attributes(&_Envelope->_ignored);
	
	UpdateBegin_init_optional_attributes(&_Envelope->_updatebegin);
	
	UpdateReady_init_optional_attributes(&_Envelope->_updateready);
	
	Chunk_init_optional_attributes(&_Envelope->_chunk);
	
	ChunkReceived_init_optional_attributes(&_Envelope->_chunkreceived);
	
	UpdateDone_init_optional_attributes(&_Envelope->_updatedone);
	
	Hello_init_optional_attributes(&_Envelope->_hello);
	
	KeyChange_init_optional_attributes(&_Envelope->_keychange);
	
}

int Envelope_is_default_message(struct Envelope *_Envelope) {
    return _Envelope->_type == 0
    
     && VariableRequest_is_default_message(&_Envelope->_variablerequest)
    
     && VariableValue_is_default_message(&_Envelope->_variablevalue)
    
     && FunctionCall_is_default_message(&_Envelope->_functioncall)
    
     && FunctionReturn_is_default_message(&_Envelope->_functionreturn)
    
     && Event_is_default_message(&_Envelope->_event)
    
     && Ignored_is_default_message(&_Envelope->_ignored)
    
     && UpdateBegin_is_default_message(&_Envelope->_updatebegin)
    
     && UpdateReady_is_default_message(&_Envelope->_updateready)
    
     && Chunk_is_default_message(&_Envelope->_chunk)
    
     && ChunkReceived_is_default_message(&_Envelope->_chunkreceived)
    
     && UpdateDone_is_default_message(&_Envelope->_updatedone)
    
     && Hello_is_default_message(&_Envelope->_hello)
    
     && KeyChange_is_default_message(&_Envelope->_keychange)
    ;
}

int Envelope_write(struct Envelope *_Envelope, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_Envelope->_type != 0) {
	    offset = Type_write_with_tag(&_Envelope->_type, _buffer, offset, 1);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!VariableRequest_is_default_message(&_Envelope->_variablerequest)) {
	    offset = VariableRequest_write_with_tag(&_Envelope->_variablerequest, _buffer, offset, 2);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!VariableValue_is_default_message(&_Envelope->_variablevalue)) {
	    offset = VariableValue_write_with_tag(&_Envelope->_variablevalue, _buffer, offset, 3);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!FunctionCall_is_default_message(&_Envelope->_functioncall)) {
	    offset = FunctionCall_write_with_tag(&_Envelope->_functioncall, _buffer, offset, 4);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!FunctionReturn_is_default_message(&_Envelope->_functionreturn)) {
	    offset = FunctionReturn_write_with_tag(&_Envelope->_functionreturn, _buffer, offset, 5);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!Event_is_default_message(&_Envelope->_event)) {
	    offset = Event_write_with_tag(&_Envelope->_event, _buffer, offset, 6);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!Ignored_is_default_message(&_Envelope->_ignored)) {
	    offset = Ignored_write_with_tag(&_Envelope->_ignored, _buffer, offset, 7);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!UpdateBegin_is_default_message(&_Envelope->_updatebegin)) {
	    offset = UpdateBegin_write_with_tag(&_Envelope->_updatebegin, _buffer, offset, 8);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!UpdateReady_is_default_message(&_Envelope->_updateready)) {
	    offset = UpdateReady_write_with_tag(&_Envelope->_updateready, _buffer, offset, 9);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!Chunk_is_default_message(&_Envelope->_chunk)) {
	    offset = Chunk_write_with_tag(&_Envelope->_chunk, _buffer, offset, 10);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!ChunkReceived_is_default_message(&_Envelope->_chunkreceived)) {
	    offset = ChunkReceived_write_with_tag(&_Envelope->_chunkreceived, _buffer, offset, 11);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!UpdateDone_is_default_message(&_Envelope->_updatedone)) {
	    offset = UpdateDone_write_with_tag(&_Envelope->_updatedone, _buffer, offset, 12);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!Hello_is_default_message(&_Envelope->_hello)) {
	    offset = Hello_write_with_tag(&_Envelope->_hello, _buffer, offset, 13);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(!KeyChange_is_default_message(&_Envelope->_keychange)) {
	    offset = KeyChange_write_with_tag(&_Envelope->_keychange, _buffer, offset, 14);
	}
	
	return offset;
}

int Envelope_write_with_tag(struct Envelope *_Envelope, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = Envelope_write_delimited_to(_Envelope, _buffer, offset);
	
	return offset;
}

int Envelope_write_delimited_to(struct Envelope *_Envelope, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = Envelope_write(_Envelope, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int Envelope_read(void *_buffer, struct Envelope *_Envelope, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	Envelope_clear(_Envelope);
	/* Assign the optional attributes. */
	Envelope_init_optional_attributes(_Envelope);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _Envelope._type */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Envelope->_type = tag;
	        	break;
	        /* tag of: _Envelope._variablerequest */
	        case 2 :
	        	offset = VariableRequest_read_delimited_from(_buffer, &_Envelope->_variablerequest, offset);
	        	break;
	        /* tag of: _Envelope._variablevalue */
	        case 3 :
	        	offset = VariableValue_read_delimited_from(_buffer, &_Envelope->_variablevalue, offset);
	        	break;
	        /* tag of: _Envelope._functioncall */
	        case 4 :
	        	offset = FunctionCall_read_delimited_from(_buffer, &_Envelope->_functioncall, offset);
	        	break;
	        /* tag of: _Envelope._functionreturn */
	        case 5 :
	        	offset = FunctionReturn_read_delimited_from(_buffer, &_Envelope->_functionreturn, offset);
	        	break;
	        /* tag of: _Envelope._event */
	        case 6 :
	        	offset = Event_read_delimited_from(_buffer, &_Envelope->_event, offset);
	        	break;
	        /* tag of: _Envelope._ignored */
	        case 7 :
	        	offset = Ignored_read_delimited_from(_buffer, &_Envelope->_ignored, offset);
	        	break;
	        /* tag of: _Envelope._updatebegin */
	        case 8 :
	        	offset = UpdateBegin_read_delimited_from(_buffer, &_Envelope->_updatebegin, offset);
	        	break;
	        /* tag of: _Envelope._updateready */
	        case 9 :
	        	offset = UpdateReady_read_delimited_from(_buffer, &_Envelope->_updateready, offset);
	        	break;
	        /* tag of: _Envelope._chunk */
	        case 10 :
	        	offset = Chunk_read_delimited_from(_buffer, &_Envelope->_chunk, offset);
	        	break;
	        /* tag of: _Envelope._chunkreceived */
	        case 11 :
	        	offset = ChunkReceived_read_delimited_from(_buffer, &_Envelope->_chunkreceived, offset);
	        	break;
	        /* tag of: _Envelope._updatedone */
	        case 12 :
	        	offset = UpdateDone_read_delimited_from(_buffer, &_Envelope->_updatedone, offset);
	        	break;
	        /* tag of: _Envelope._hello */
	        case 13 :
	        	offset = Hello_read_delimited_from(_buffer, &_Envelope->_hello, offset);
	        	break;
	        /* tag of: _Envelope._keychange */
	        case 14 :
	        	offset = KeyChange_read_delimited_from(_buffer, &_Envelope->_keychange, offset);
	        	break;
	    }
	}
	
	return offset;
}

int Envelope_read_delimited_from(void *_buffer, struct Envelope *_Envelope, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	Envelope_read(_buffer, _Envelope, offset, size + offset);
	
	return offset + size;
}
