/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : chunk.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Chunk.h"

/*******************************************************************
 * Message: Chunk.proto, line 5
 *******************************************************************/

void Chunk_clear(struct Chunk *_Chunk) {
	_memset(_Chunk, 0, sizeof(struct Chunk));
}

void Chunk_init_optional_attributes(struct Chunk *_Chunk) {
	_Chunk->_crc_len = 0;
	
	
	_Chunk->_length = 0;
	
	_Chunk->_data_len = 0;
	
	
}

int Chunk_is_default_message(struct Chunk *_Chunk) {
    return _Chunk->_crc_len == 0
    
     && _Chunk->_length == 0
    
     && _Chunk->_data_len == 0
    ;
}

int Chunk_write(struct Chunk *_Chunk, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_Chunk->_crc_len != 1
	    || _Chunk->_crc[0] != '0') {
		offset = write_raw_varint32((1<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_Chunk->_crc_len, _buffer, offset);
	    offset = write_raw_bytes(_Chunk->_crc, _Chunk->_crc_len, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Chunk->_length != 0) {
		offset = write_raw_varint32((2<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Chunk->_length, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Chunk->_data_len != 1
	    || _Chunk->_data[0] != '0') {
		offset = write_raw_varint32((3<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_Chunk->_data_len, _buffer, offset);
	    offset = write_raw_bytes(_Chunk->_data, _Chunk->_data_len, _buffer, offset);
	}
	
	return offset;
}

int Chunk_write_with_tag(struct Chunk *_Chunk, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = Chunk_write_delimited_to(_Chunk, _buffer, offset);
	
	return offset;
}

int Chunk_write_delimited_to(struct Chunk *_Chunk, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = Chunk_write(_Chunk, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int Chunk_read(void *_buffer, struct Chunk *_Chunk, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	Chunk_clear(_Chunk);
	/* Assign the optional attributes. */
	Chunk_init_optional_attributes(_Chunk);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _Chunk._crc */
	        case 1 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Chunk->_crc_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_Chunk->_crc + i), _buffer, offset);
	        	break;
	        /* tag of: _Chunk._length */
	        case 2 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Chunk->_length = tag;
	        	break;
	        /* tag of: _Chunk._data */
	        case 3 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Chunk->_data_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_Chunk->_data + i), _buffer, offset);
	        	break;
	    }
	}
	
	return offset;
}

int Chunk_read_delimited_from(void *_buffer, struct Chunk *_Chunk, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	Chunk_read(_buffer, _Chunk, offset, size + offset);
	
	return offset + size;
}
