/******************************************************************* 
 * Header file generated by Protoc for Embedded C.                 *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : Chunk_received.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/

#ifndef _Chunk_received_H
#define _Chunk_received_H

#ifdef __cplusplus
  extern "C" {
#endif

#define MAX_BYTES_LENGTH 32

/*******************************************************************
 * Message: Chunk_received.proto, line 5
 *******************************************************************/

/* Maximum size of a serialized ChunkReceived-message, useful for buffer allocation. */
#define MAX_ChunkReceived_SIZE 44

/* Structure that holds a deserialized ChunkReceived-message. */
struct ChunkReceived {
    unsigned long _counter;
    int _crc_len;
    char _crc[MAX_BYTES_LENGTH];
};

/*
 * Serialize a Person-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int ChunkReceived_write_delimited_to(struct ChunkReceived *_ChunkReceived, void *_buffer, int offset);

/*
 * Serialize a Person-message together with its tag into the given buffer 
 * at offset and return new offset for optional next message.
 * Is useful if a Person-message is embedded in another message.
 */
int ChunkReceived_write_with_tag(struct ChunkReceived *_ChunkReceived, void *_buffer, int offset, int tag);

/*
 * Deserialize a Person-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _Person will be reset to 0 before _buffer is interpreted.
 */
int ChunkReceived_read_delimited_from(void *_buffer, struct ChunkReceived *_ChunkReceived, int offset);



#ifdef __cplusplus
  }
#endif

#endif

