/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : chunk_received.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Chunk_received.h"

/*******************************************************************
 * Message: Chunk_received.proto, line 5
 *******************************************************************/

void ChunkReceived_clear(struct ChunkReceived *_ChunkReceived) {
	_memset(_ChunkReceived, 0, sizeof(struct ChunkReceived));
}

void ChunkReceived_init_optional_attributes(struct ChunkReceived *_ChunkReceived) {
	_ChunkReceived->_counter = 0;
	
	_ChunkReceived->_crc_len = 0;
	
	
}

int ChunkReceived_is_default_message(struct ChunkReceived *_ChunkReceived) {
    return _ChunkReceived->_counter == 0
    
     && _ChunkReceived->_crc_len == 0
    ;
}

int ChunkReceived_write(struct ChunkReceived *_ChunkReceived, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_ChunkReceived->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_ChunkReceived->_counter, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_ChunkReceived->_crc_len != 1
	    || _ChunkReceived->_crc[0] != '0') {
		offset = write_raw_varint32((2<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_ChunkReceived->_crc_len, _buffer, offset);
	    offset = write_raw_bytes(_ChunkReceived->_crc, _ChunkReceived->_crc_len, _buffer, offset);
	}
	
	return offset;
}

int ChunkReceived_write_with_tag(struct ChunkReceived *_ChunkReceived, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = ChunkReceived_write_delimited_to(_ChunkReceived, _buffer, offset);
	
	return offset;
}

int ChunkReceived_write_delimited_to(struct ChunkReceived *_ChunkReceived, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = ChunkReceived_write(_ChunkReceived, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int ChunkReceived_read(void *_buffer, struct ChunkReceived *_ChunkReceived, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	ChunkReceived_clear(_ChunkReceived);
	/* Assign the optional attributes. */
	ChunkReceived_init_optional_attributes(_ChunkReceived);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _ChunkReceived._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_ChunkReceived->_counter = tag;
	        	break;
	        /* tag of: _ChunkReceived._crc */
	        case 2 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_ChunkReceived->_crc_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_ChunkReceived->_crc + i), _buffer, offset);
	        	break;
	    }
	}
	
	return offset;
}

int ChunkReceived_read_delimited_from(void *_buffer, struct ChunkReceived *_ChunkReceived, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	ChunkReceived_read(_buffer, _ChunkReceived, offset, size + offset);
	
	return offset + size;
}
