/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : event.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Event.h"

/*******************************************************************
 * Message: Event.proto, line 5
 *******************************************************************/

void Event_clear(struct Event *_Event) {
	_memset(_Event, 0, sizeof(struct Event));
}

void Event_init_optional_attributes(struct Event *_Event) {
	_Event->_counter = 0;
	
	_Event->_name_len = 0;
	
	
	_Event->_data_len = 0;
	
	
}

int Event_is_default_message(struct Event *_Event) {
    return _Event->_counter == 0
    
     && _Event->_name_len == 0
    
     && _Event->_data_len == 0
    ;
}

int Event_write(struct Event *_Event, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_Event->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Event->_counter, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Event->_name_len != 1
	    || _Event->_name[0] != '0') {
		offset = write_raw_varint32((2<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_Event->_name_len, _buffer, offset);
	    offset = write_raw_bytes(_Event->_name, _Event->_name_len, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Event->_data_len != 1
	    || _Event->_data[0] != '0') {
		offset = write_raw_varint32((3<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_Event->_data_len, _buffer, offset);
	    offset = write_raw_bytes(_Event->_data, _Event->_data_len, _buffer, offset);
	}
	
	return offset;
}

int Event_write_with_tag(struct Event *_Event, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = Event_write_delimited_to(_Event, _buffer, offset);
	
	return offset;
}

int Event_write_delimited_to(struct Event *_Event, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = Event_write(_Event, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int Event_read(void *_buffer, struct Event *_Event, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	Event_clear(_Event);
	/* Assign the optional attributes. */
	Event_init_optional_attributes(_Event);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _Event._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Event->_counter = tag;
	        	break;
	        /* tag of: _Event._name */
	        case 2 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Event->_name_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_Event->_name + i), _buffer, offset);
	        	break;
	        /* tag of: _Event._data */
	        case 3 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Event->_data_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_Event->_data + i), _buffer, offset);
	        	break;
	    }
	}
	
	return offset;
}

int Event_read_delimited_from(void *_buffer, struct Event *_Event, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	Event_read(_buffer, _Event, offset, size + offset);
	
	return offset + size;
}
