/******************************************************************* 
 * Header file generated by Protoc for Embedded C.                 *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : Event.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/

#ifndef _Event_H
#define _Event_H

#ifdef __cplusplus
  extern "C" {
#endif

#define MAX_STRING_LENGTH 32

/*******************************************************************
 * Message: Event.proto, line 5
 *******************************************************************/

/* Maximum size of a serialized Event-message, useful for buffer allocation. */
#define MAX_Event_SIZE 79

/* Structure that holds a deserialized Event-message. */
struct Event {
    unsigned long _counter;
    int _name_len;
    char _name[MAX_STRING_LENGTH];
    int _data_len;
    char _data[MAX_STRING_LENGTH];
};

/*
 * Serialize a Person-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int Event_write_delimited_to(struct Event *_Event, void *_buffer, int offset);

/*
 * Serialize a Person-message together with its tag into the given buffer 
 * at offset and return new offset for optional next message.
 * Is useful if a Person-message is embedded in another message.
 */
int Event_write_with_tag(struct Event *_Event, void *_buffer, int offset, int tag);

/*
 * Deserialize a Person-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _Person will be reset to 0 before _buffer is interpreted.
 */
int Event_read_delimited_from(void *_buffer, struct Event *_Event, int offset);



#ifdef __cplusplus
  }
#endif

#endif

