/******************************************************************* 
 * Header file generated by Protoc for Embedded C.                 *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : Function_return.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/

#ifndef _Function_return_H
#define _Function_return_H

#ifdef __cplusplus
  extern "C" {
#endif

/*******************************************************************
 * Message: Function_return.proto, line 3
 *******************************************************************/

/* Maximum size of a serialized FunctionReturn-message, useful for buffer allocation. */
#define MAX_FunctionReturn_SIZE 9

/* Structure that holds a deserialized FunctionReturn-message. */
struct FunctionReturn {
    unsigned long _counter;
};

/*
 * Serialize a Person-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int FunctionReturn_write_delimited_to(struct FunctionReturn *_FunctionReturn, void *_buffer, int offset);

/*
 * Serialize a Person-message together with its tag into the given buffer 
 * at offset and return new offset for optional next message.
 * Is useful if a Person-message is embedded in another message.
 */
int FunctionReturn_write_with_tag(struct FunctionReturn *_FunctionReturn, void *_buffer, int offset, int tag);

/*
 * Deserialize a Person-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _Person will be reset to 0 before _buffer is interpreted.
 */
int FunctionReturn_read_delimited_from(void *_buffer, struct FunctionReturn *_FunctionReturn, int offset);



#ifdef __cplusplus
  }
#endif

#endif

