/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : function_call.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Function_call.h"

/*******************************************************************
 * Message: Function_call.proto, line 3
 *******************************************************************/

void FunctionCall_clear(struct FunctionCall *_FunctionCall) {
	_memset(_FunctionCall, 0, sizeof(struct FunctionCall));
}

void FunctionCall_init_optional_attributes(struct FunctionCall *_FunctionCall) {
	_FunctionCall->_counter = 0;
	
}

int FunctionCall_is_default_message(struct FunctionCall *_FunctionCall) {
    return _FunctionCall->_counter == 0
    ;
}

int FunctionCall_write(struct FunctionCall *_FunctionCall, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_FunctionCall->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_FunctionCall->_counter, _buffer, offset);
	}
	
	return offset;
}

int FunctionCall_write_with_tag(struct FunctionCall *_FunctionCall, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = FunctionCall_write_delimited_to(_FunctionCall, _buffer, offset);
	
	return offset;
}

int FunctionCall_write_delimited_to(struct FunctionCall *_FunctionCall, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = FunctionCall_write(_FunctionCall, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int FunctionCall_read(void *_buffer, struct FunctionCall *_FunctionCall, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	FunctionCall_clear(_FunctionCall);
	/* Assign the optional attributes. */
	FunctionCall_init_optional_attributes(_FunctionCall);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _FunctionCall._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_FunctionCall->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int FunctionCall_read_delimited_from(void *_buffer, struct FunctionCall *_FunctionCall, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	FunctionCall_read(_buffer, _FunctionCall, offset, size + offset);
	
	return offset + size;
}
