/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : function_return.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Function_return.h"

/*******************************************************************
 * Message: Function_return.proto, line 3
 *******************************************************************/

void FunctionReturn_clear(struct FunctionReturn *_FunctionReturn) {
	_memset(_FunctionReturn, 0, sizeof(struct FunctionReturn));
}

void FunctionReturn_init_optional_attributes(struct FunctionReturn *_FunctionReturn) {
	_FunctionReturn->_counter = 0;
	
}

int FunctionReturn_is_default_message(struct FunctionReturn *_FunctionReturn) {
    return _FunctionReturn->_counter == 0
    ;
}

int FunctionReturn_write(struct FunctionReturn *_FunctionReturn, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_FunctionReturn->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_FunctionReturn->_counter, _buffer, offset);
	}
	
	return offset;
}

int FunctionReturn_write_with_tag(struct FunctionReturn *_FunctionReturn, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = FunctionReturn_write_delimited_to(_FunctionReturn, _buffer, offset);
	
	return offset;
}

int FunctionReturn_write_delimited_to(struct FunctionReturn *_FunctionReturn, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = FunctionReturn_write(_FunctionReturn, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int FunctionReturn_read(void *_buffer, struct FunctionReturn *_FunctionReturn, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	FunctionReturn_clear(_FunctionReturn);
	/* Assign the optional attributes. */
	FunctionReturn_init_optional_attributes(_FunctionReturn);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _FunctionReturn._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_FunctionReturn->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int FunctionReturn_read_delimited_from(void *_buffer, struct FunctionReturn *_FunctionReturn, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	FunctionReturn_read(_buffer, _FunctionReturn, offset, size + offset);
	
	return offset + size;
}
