/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : ignored.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Ignored.h"

/*******************************************************************
 * Message: Ignored.proto, line 3
 *******************************************************************/

void Ignored_clear(struct Ignored *_Ignored) {
	_memset(_Ignored, 0, sizeof(struct Ignored));
}

void Ignored_init_optional_attributes(struct Ignored *_Ignored) {
	_Ignored->_counter = 0;
	
	_Ignored->_received = 0;
	
}

int Ignored_is_default_message(struct Ignored *_Ignored) {
    return _Ignored->_counter == 0
    
     && _Ignored->_received == 0
    ;
}

int Ignored_write(struct Ignored *_Ignored, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_Ignored->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Ignored->_counter, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Ignored->_received != 0) {
		offset = write_raw_varint32((2<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Ignored->_received, _buffer, offset);
	}
	
	return offset;
}

int Ignored_write_with_tag(struct Ignored *_Ignored, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = Ignored_write_delimited_to(_Ignored, _buffer, offset);
	
	return offset;
}

int Ignored_write_delimited_to(struct Ignored *_Ignored, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = Ignored_write(_Ignored, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int Ignored_read(void *_buffer, struct Ignored *_Ignored, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	Ignored_clear(_Ignored);
	/* Assign the optional attributes. */
	Ignored_init_optional_attributes(_Ignored);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _Ignored._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Ignored->_counter = tag;
	        	break;
	        /* tag of: _Ignored._received */
	        case 2 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Ignored->_received = tag;
	        	break;
	    }
	}
	
	return offset;
}

int Ignored_read_delimited_from(void *_buffer, struct Ignored *_Ignored, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	Ignored_read(_buffer, _Ignored, offset, size + offset);
	
	return offset + size;
}
