/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : update_done.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Update_done.h"

/*******************************************************************
 * Message: Update_done.proto, line 3
 *******************************************************************/

void UpdateDone_clear(struct UpdateDone *_UpdateDone) {
	_memset(_UpdateDone, 0, sizeof(struct UpdateDone));
}

void UpdateDone_init_optional_attributes(struct UpdateDone *_UpdateDone) {
	_UpdateDone->_counter = 0;
	
}

int UpdateDone_is_default_message(struct UpdateDone *_UpdateDone) {
    return _UpdateDone->_counter == 0
    ;
}

int UpdateDone_write(struct UpdateDone *_UpdateDone, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_UpdateDone->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_UpdateDone->_counter, _buffer, offset);
	}
	
	return offset;
}

int UpdateDone_write_with_tag(struct UpdateDone *_UpdateDone, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = UpdateDone_write_delimited_to(_UpdateDone, _buffer, offset);
	
	return offset;
}

int UpdateDone_write_delimited_to(struct UpdateDone *_UpdateDone, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = UpdateDone_write(_UpdateDone, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int UpdateDone_read(void *_buffer, struct UpdateDone *_UpdateDone, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	UpdateDone_clear(_UpdateDone);
	/* Assign the optional attributes. */
	UpdateDone_init_optional_attributes(_UpdateDone);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _UpdateDone._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_UpdateDone->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int UpdateDone_read_delimited_from(void *_buffer, struct UpdateDone *_UpdateDone, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	UpdateDone_read(_buffer, _UpdateDone, offset, size + offset);
	
	return offset + size;
}
