/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : update_ready.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Update_ready.h"

/*******************************************************************
 * Message: Update_ready.proto, line 3
 *******************************************************************/

void UpdateReady_clear(struct UpdateReady *_UpdateReady) {
	_memset(_UpdateReady, 0, sizeof(struct UpdateReady));
}

void UpdateReady_init_optional_attributes(struct UpdateReady *_UpdateReady) {
	_UpdateReady->_counter = 0;
	
}

int UpdateReady_is_default_message(struct UpdateReady *_UpdateReady) {
    return _UpdateReady->_counter == 0
    ;
}

int UpdateReady_write(struct UpdateReady *_UpdateReady, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_UpdateReady->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_UpdateReady->_counter, _buffer, offset);
	}
	
	return offset;
}

int UpdateReady_write_with_tag(struct UpdateReady *_UpdateReady, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = UpdateReady_write_delimited_to(_UpdateReady, _buffer, offset);
	
	return offset;
}

int UpdateReady_write_delimited_to(struct UpdateReady *_UpdateReady, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = UpdateReady_write(_UpdateReady, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int UpdateReady_read(void *_buffer, struct UpdateReady *_UpdateReady, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	UpdateReady_clear(_UpdateReady);
	/* Assign the optional attributes. */
	UpdateReady_init_optional_attributes(_UpdateReady);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _UpdateReady._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_UpdateReady->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int UpdateReady_read_delimited_from(void *_buffer, struct UpdateReady *_UpdateReady, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	UpdateReady_read(_buffer, _UpdateReady, offset, size + offset);
	
	return offset + size;
}
