/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : variable_value.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Variable_value.h"

/*******************************************************************
 * Message: Variable_value.proto, line 3
 *******************************************************************/

void VariableValue_clear(struct VariableValue *_VariableValue) {
	_memset(_VariableValue, 0, sizeof(struct VariableValue));
}

void VariableValue_init_optional_attributes(struct VariableValue *_VariableValue) {
	_VariableValue->_counter = 0;
	
}

int VariableValue_is_default_message(struct VariableValue *_VariableValue) {
    return _VariableValue->_counter == 0
    ;
}

int VariableValue_write(struct VariableValue *_VariableValue, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_VariableValue->_counter != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_VariableValue->_counter, _buffer, offset);
	}
	
	return offset;
}

int VariableValue_write_with_tag(struct VariableValue *_VariableValue, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = VariableValue_write_delimited_to(_VariableValue, _buffer, offset);
	
	return offset;
}

int VariableValue_write_delimited_to(struct VariableValue *_VariableValue, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = VariableValue_write(_VariableValue, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int VariableValue_read(void *_buffer, struct VariableValue *_VariableValue, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	VariableValue_clear(_VariableValue);
	/* Assign the optional attributes. */
	VariableValue_init_optional_attributes(_VariableValue);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _VariableValue._counter */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_VariableValue->_counter = tag;
	        	break;
	    }
	}
	
	return offset;
}

int VariableValue_read_delimited_from(void *_buffer, struct VariableValue *_VariableValue, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	VariableValue_read(_buffer, _VariableValue, offset, size + offset);
	
	return offset + size;
}
