/******************************************************************* 
 * Header file generated by Protoc for Embedded C.                 *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : Variable_value.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/

#ifndef _Variable_value_H
#define _Variable_value_H

#ifdef __cplusplus
  extern "C" {
#endif

/*******************************************************************
 * Message: Variable_value.proto, line 3
 *******************************************************************/

/* Maximum size of a serialized VariableValue-message, useful for buffer allocation. */
#define MAX_VariableValue_SIZE 9

/* Structure that holds a deserialized VariableValue-message. */
struct VariableValue {
    unsigned long _counter;
};

/*
 * Serialize a Person-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int VariableValue_write_delimited_to(struct VariableValue *_VariableValue, void *_buffer, int offset);

/*
 * Serialize a Person-message together with its tag into the given buffer 
 * at offset and return new offset for optional next message.
 * Is useful if a Person-message is embedded in another message.
 */
int VariableValue_write_with_tag(struct VariableValue *_VariableValue, void *_buffer, int offset, int tag);

/*
 * Deserialize a Person-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _Person will be reset to 0 before _buffer is interpreted.
 */
int VariableValue_read_delimited_from(void *_buffer, struct VariableValue *_VariableValue, int offset);



#ifdef __cplusplus
  }
#endif

#endif

